SELECT NULL + 10 FROM dual;

SELECT NVL(NULL, 100) AS result
FROM dual;

SELECT NAME,
       NVL(SALARY, 0) AS SALARY
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE SALARY IS NULL;

UPDATE EMPLOYEES
SET SALARY = NULL
WHERE NAME = 'Alice';

UPDATE EMPLOYEES
SET SALARY = NULL
WHERE NAME = 'Bob';
