CREATE TABLE EMPLOYEES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    DEPARTMENT VARCHAR2(50),
    SALARY NUMBER(15,7),
    HIRE_DATE DATE
);

INSERT INTO EMPLOYEES VALUES (
    1,
    'Alice',
    'HR',
    60000.7685000,
    DATE '2020-01-15'
);

INSERT INTO EMPLOYEES VALUES (
    2,
    'Bob',
    'IT',
    50000.1234000,
    DATE '2021-05-10'
);

INSERT INTO EMPLOYEES VALUES (
    3,
    'Charlie',
    'Finance',
    55000.5678000,
    DATE '2022-08-20'
);

INSERT INTO EMPLOYEES VALUES (
    4,
    'David',
    'Marketing',
    45000.4321000,
    DATE '2023-12-01'
);

DROP TABLE EMPLOYEES;

SELECT *
FROM EMPLOYEES;

SELECT sysdate AS current_date
FROM DUAL;

SELECT CURRENT_DATE
FROM DUAL;

SELECT *
FROM EMPLOYEES;

SELECT NAME,
		 HIRE_DATE,
		 ROUND(SYSDATE - HIRE_DATE) AS DAYS_EMPLOYED
FROM EMPLOYEES;

SELECT NAME,
       HIRE_DATE,
       ADD_MONTHS(HIRE_DATE, 6) AS REVIEW_DATE
FROM EMPLOYEES;

SELECT ADD_MONTHS(HIRE_DATE, -3) AS REVIEW_DATE
FROM EMPLOYEES;

SELECT NAME,
		MONTHS_BETWEEN(SYSDATE, HIRE_DATE) AS MONTHS_EMPLOYED
FROM EMPLOYEES;

SELECT NAME,
		ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE), 2) AS MONTHS_EMPLOYED
FROM EMPLOYEES;
