-- Create a table named CUSTOMERS
CREATE TABLE CUSTOMERS (
	 ID INT NOT NULL PRIMARY KEY,
	 NAME VARCHAR(255) NOT NULL,
	 AGE INT NOT NULL,
	 ADDRESS VARCHAR(255),
	 SALARY DECIMAL(18, 2)
);

-- Insert some sample data into the CUSTOMERS table
INSERT INTO CUSTOMERS (ID, NAME,AGE, ADDRESS, SALARY)
VALUES (1, 'JAKIR', 30, '123 Main St', 50000.00);
INSERT INTO CUSTOMERS (ID, NAME,AGE, ADDRESS, SALARY)
VALUES (2, 'MASUD', 25, '456 Elm St', 60000.00);
INSERT INTO CUSTOMERS (ID, NAME,AGE, ADDRESS, SALARY)
VALUES (3, 'KABIR', 35, '789 Oak St', 55000.00);
INSERT INTO CUSTOMERS (ID, NAME,AGE, ADDRESS, SALARY)
VALUES (4, 'FAHIM', 28, '101 Pine St', 52000.00);

-- Query the CUSTOMERS table to verify the data
SELECT * FROM CUSTOMERS;

-- SELECT INTO clause
DECLARE
C_ID CUSTOMERS.ID%TYPE := 2;
C_NAME CUSTOMERS.NAME%TYPE;
C_AGE CUSTOMERS.AGE%TYPE;
C_ADDRESS CUSTOMERS.ADDRESS%TYPE;
C_SALARY CUSTOMERS.SALARY%TYPE;
BEGIN
SELECT NAME, AGE, ADDRESS, SALARY INTO C_NAME, C_AGE, C_ADDRESS, C_SALARY
FROM CUSTOMERS
WHERE ID = C_ID;
DBMS_OUTPUT.PUT_LINE('Customer Name: ' || C_NAME);
DBMS_OUTPUT.PUT_LINE('Customer Age: ' || C_AGE);
DBMS_OUTPUT.PUT_LINE('Customer Address: ' || C_ADDRESS);
DBMS_OUTPUT.PUT_LINE('Customer Salary: ' || C_SALARY);
END;
/
