SELECT COUNT(*) AS total_employees
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT) AS total_departments
FROM EMPLOYEES;

SELECT COUNT(SALARY) AS total_salaries
FROM EMPLOYEES;

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

SELECT DEPARTMENT,
		 SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
       COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
       AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;
