-- Create a data table for string functions examples
CREATE TABLE STRING_FUNCTIONS_DATA_TABLE (
	 ID NUMBER PRIMARY KEY,
	 NAME VARCHAR2(50),
	 SALARY NUMBER,
	 PHONE VARCHAR2(20)
);

-- Insert sample data into the table
INSERT INTO STRING_FUNCTIONS_DATA_TABLE (ID, NAME, SALARY, PHONE)
VALUES (1, 'Alice Johnson', 60000, '123-456-7890');
INSERT INTO STRING_FUNCTIONS_DATA_TABLE (ID, NAME, SALARY, PHONE)
VALUES (2, 'Bob Smith', 45000, '234-567-8901');
INSERT INTO STRING_FUNCTIONS_DATA_TABLE (ID, NAME, SALARY, PHONE)
VALUES (3, 'Charlie Brown', 55000, '345-678-9012');
INSERT INTO STRING_FUNCTIONS_DATA_TABLE (ID, NAME, SALARY, PHONE)
VALUES (4, 'Diana Prince', 70000, '456-789-0123');
INSERT INTO STRING_FUNCTIONS_DATA_TABLE (ID, NAME, SALARY, PHONE)
VALUES (5, 'Ethan Hunt', 50000, '567-890-1234');

-- SHOW the data in the table
SELECT * FROM STRING_FUNCTIONS_DATA_TABLE;

UPDATE STRING_FUNCTIONS_DATA_TABLE
SET EMAIL = 'charliebrown@example.com'
WHERE ID = 3;

-- USE this functions
SELECT NAME,
       UPPER(NAME) AS UPPER_NAME,
		 LOWER(NAME) AS LOWER_NAME,
		 INITCAP(NAME) AS INITCAP_NAME
FROM STRING_FUNCTIONS_DATA_TABLE;

UPDATE STRING_FUNCTIONS_DATA_TABLE
SET NAME = 'alice johnson'
WHERE ID = 1;

-- email format validation
SELECT NAME, PHONE,
		 CASE
			  WHEN REGEXP_LIKE(PHONE, '^\d{3}-\d{3}-\d{4}$') THEN 'Valid'
			  ELSE 'Invalid'
		 END AS PHONE_VALIDATION
FROM STRING_FUNCTIONS_DATA_TABLE;

ALTER TABLE STRING_FUNCTIONS_DATA_TABLE
ADD EMAIL VARCHAR2(50);
